#pragma once

#include "Drawables/Interface/GameOverDrawable.h"
#include "Drawables/Interface/LeftTanksDrawable.h"
#include "Drawables/Interface/PlayerLivesDrawable.h"
#include "Drawables/Interface/StageNumberDrawable.h"
#include "Drawables/Playfield/BorderDrawable.h"
#include "Drawables/Playfield/BrickDrawable.h"
#include "Drawables/Playfield/BushDrawable.h"
#include "Drawables/Playfield/EagleDrawable.h"
#include "Drawables/Playfield/TankSpawnerDrawable.h"
#include "Drawables/Playfield/WaterDrawable.h"
#include "Drawables/Playfield/WallDrawable.h"
#include "Drawables/Tank/BonusDrawable.h"
#include "Drawables/Tank/BulletDrawable.h"
#include "Drawables/Tank/ExplosionDrawable.h"
#include "Drawables/Tank/ProtectionDrawable.h"
#include "Drawables/Tank/TankDrawable.h"
