name: Testing

on:
  push:
    branches: [main, beta2]
  pull_request:
    branches: [main]

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing dependencies
        if: runner.os == 'Linux'
        working-directory: ./
        run: sudo apt -y install
          build-essential make cmake
          libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev
          libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev
          libfreetype-dev

      - name: Build project
        working-directory: ./
        run: make ${{ runner.os }} -e FORCE_FETCH_CONTENT=1
