name: Testing

on:
  push:
    branches: [main, beta2]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        working-directory: ./
        run: sudo apt -y install
          build-essential make cmake
          libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev
          libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev
          libfreetype-dev

      - name: Build project
        working-directory: ./
        run: make linux -e FORCE_FETCH_CONTENT=1

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        working-directory: ./
        run: |
          choco install visualstudio2017buildtools --version 15.9.28307.1038 --params "'/Install /NoWeb /Add Microsoft.VisualStudio.Workload.VCTools /IncludeRecommended /IncludeOptional /Add Microsoft.VisualStudio.Component.Windows10SDK.17134'"
          "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Installer/vs_install.exe" --add Microsoft.VisualStudio.Component.VC.v141.xp --quiet --wait --norestart

      - name: Build project
        working-directory: ./
        run: make win -e FORCE_FETCH_CONTENT=1

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        working-directory: ./
        run: make darwin -e FORCE_FETCH_CONTENT=1