name: Testing

on:
  push:
    branches: [main, beta2]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        working-directory: ./
        run: make linux -f ./Makefile_github

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        working-directory: ./
        run: make win -f ./Makefile_github

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        working-directory: ./
        run: make darwin -f ./Makefile_github