#include <string>
#include "Config.h"

/*
*   - air (nothing)
* b - brick
* w - wall
* B - bush
* i - ice
* W - water
* p - "protection"
* e - eagle (upper left corner)
*/

const std::string stages[36][26] = {
{ // STAGE 1
	"                          ",
	"                          ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bbwwbb  bb  bb  ",
	"  bb  bb  bbwwbb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb          bb  bb  ",
	"  bb  bb          bb  bb  ",
	"          bb  bb          ",
	"          bb  bb          ",
	"bb  bbbb          bbbb  bb",
	"ww  bbbb          bbbb  ww",
	"          bb  bb          ",
	"          bbbbbb          ",
	"  bb  bb  bbbbbb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb          bb  bb  ",
	"  bb  bb          bb  bb  ",
	"  bb  bb   pppp   bb  bb  ",
	"           pe p           ",
	"           p  p           "
},
{ // STAGE 2
	"      ww      ww          ",
	"      ww      ww          ",
	"  bb  ww      bb  bb  bb  ",
	"  bb  ww      bb  bb  bb  ",
	"  bb        bbbb  bbwwbb  ",
	"  bb        bbbb  bbwwbb  ",
	"      bb          ww      ",
	"      bb          ww      ",
	"BB    bb    ww    bbBBbbww",
	"BB    bb    ww    bbBBbbww",
	"BBBB      bb    ww  BB    ",
	"BBBB      bb    ww  BB    ",
	"  bbbbbbBBBBBBww    BBbb  ",
	"  bbbbbbBBBBBBww    BBbb  ",
	"      wwBBbb  bb  bb  bb  ",
	"      wwBBbb  bb  bb  bb  ",
	"wwbb  ww  bb  bb      bb  ",
	"wwbb  ww  bb  bb      bb  ",
	"  bb  bb  bbbbbb  bbwwbb  ",
	"  bb  bb  bbbbbb  bbwwbb  ",
	"  bb  bb  bbbbbb          ",
	"  bb  bb  bbbbbb          ",
	"  bb              bb  bb  ",
	"  bb       pppp   bb  bb  ",
	"  bb  bb   pe p   bbbbbb  ",
	"  bb  bb   p  p   bbbbbb  "
},
{ // STAGE 3
	"        bb      bb        ",
	"        bb      bb        ",
	"  BBBBBBbb                ",
	"  BBBBBBbb          wwwwww",
	"bbBBBBBB                  ",
	"bbBBBBBB                  ",
	"BBBBBBBB      bb  bbbbbbb ",
	"BBBBBBBB      bb  bbbbbbb ",
	"BBBBBBBBbbbbbbbb  bb   b  ",
	"BBBBBBBBbbbbbb    bb   b  ",
	"BBBBBBBB    bb         b  ",
	"BBBBBBBB    bb         b  ",
	"  BB        wwwwww    BB  ",
	"  BB        wwwwww    BB  ",
	"                  BBBBBBBB",
	"  bb  bb          BBBBBBBB",
	"bbb  bbbb  bbbbbbbBBBBBBBB",
	"bbb  bbbb  b      BBBBBBBB",
	"          bb      BBBBBBBB",
	"          bb  bbbbBBBBBBBB",
	"bb    w       bbbbBBBBBB  ",
	"bb    w           BBBBBB  ",
	"bbbb  w           BBBBBB  ",
	"bbbb  w    pppp   BBBBBB  ",
	"wwbbbb     pe p   bb      ",
	"wwbbbb     p  p   bb      "
},
{ // STAGE 4
	"  BBBB                BB  ",
	"  BBBB                BB  ",
	"BBBB      bbbb          BB",
	"BBBB    bbbbbbbbbb      BB",
	"BB     bbbbbbbbbbbbb    ww",
	"BB     bbbbbbbbbbbbbbb    ",
	"ww    bbbbbbbbbbbbbbbbb   ",
	"      bbbbbbbbbbbbbbbbb   ",
	"     bbb      bbbbbb  b   ",
	"     b          bbbb  b   ",
	"WW   b  w   w   bbb       ",
	"WW   b  w   w   bbb       ",
	"    bb          bbb   WWWW",
	"    bb  bbbb    bbb   WWWW",
	"    bbbbbbbbbbbbbbbb      ",
	"    bbbbbbbbbbbbbbbb      ",
	"   bbbbbbbbbbbbbbbbbb     ",
	"   bbbbbbbbbbbbbbbbbb     ",
	"  bbbbbbbbbbbbbbbbbbbb    ",
	"      bbbbbbbbbbbb        ",
	"  bbbb  bbbbbbbb  bbbb  BB",
	"  bbbbbb  bbbb  bbbbbb  BB",
	"BB  bbbb        bbbb  BBBB",
	"BB         pppp       BBBB",
	"wwBB       pe p     BBBBww",
	"wwBB       p  p     BBBBww"
},
{ // STAGE 5
	"        bbbb              ",
	"        bbbb              ",
	"        bb      wwwwww    ",
	"ww  bb  bb          ww    ",
	"ww  bb      bb            ",
	"ww  bb      bb            ",
	"bb  bbbbbb  bbbb  WWWW  WW",
	"bb  bbbbbb  bbbb  WWWW  WW",
	"bb      bb        WW      ",
	"                  WW      ",
	"        WWWW  WWWWWW  bbbb",
	"    bb  WWWW  WWWWWW  bbbb",
	"bbbb    WWbb  bbb         ",
	"bbbb    WWbb  bbb         ",
	"        WW           ww   ",
	"        WW           ww   ",
	"WWWWWW  WW  ww  bb   w    ",
	"WWWWWW  WW  ww  bb   w    ",
	"                     wbbbb",
	"      bbbb           wbbbb",
	"        bbbbbbbbbb        ",
	"        bb      bbbb      ",
	"bbbbbb            bbbb    ",
	"bbbb       pppp     bb    ",
	"bb         pe p           ",
	"           p  p           "
},
{ // STAGE 6
	"           b  b BBBB      ",
	"           b  b BBBB      ",
	"  b  w  b        bBBb  bBB",
	"  b  w  b        bBBb  bBB",
	"  b  w  b   bb   bBBb  bBB",
	"  b  w  b   bb   bBBb  bBB ",
	"  bb    bb  ww  bbBB  bbBB",
	"  bb    bb  ww  bbBB  bbBB",
	"       bww  bb  bbw   BBBB",
	"       b    bb    w   BBBB",
	"bbbbb     BBbbBB     bbbbb",
	"bbbbb     BBbbBB     bbbbb",
	"         bBBBBBBb         ",
	"         bBBBBBBb         ",
	"wwbbbb  bbBBBBBBbb bbbbbww",
	"wwbbbb    BBBBBB   bbbbbww",
	"wwwwww      BB      wwwwww",
	"        bb  BB  bb        ",
	"  bb    bb      bb        ",
	"  bb    bb      bb        ",
	"  bbb     bb  bb     bbbBB",
	"  bbb                bbbBB",
	"    bb              BBBBBB",
	"           pppp     BBBBBB",
	"           pe p       BBBB",
	"    bb     p  p     bbBBBB"
},
{ // STAGE 7
	"              wwww        ",
	"                          ",
	"    wwwwwwww        ww    ",
	"    ww              ww    ",
	"    ww      BB  wwwwww    ",
	"    ww      BB    wwww    ",
	"  ww      BBww      ww    ",
	"  ww      BBww      ww    ",
	"        BBwwww      wwww  ",
	"        BBwwww        ww  ",
	"  ww  BBwwwwww  ww        ",
	"  ww  BBwwwwww  ww        ",
	"   w  wwww      wwww      ",
	"   w  wwww      wwww      ",
	"w       ww  wwwwww     w  ",
	"w       ww  wwwwww     w  ",
	"   www      wwwwBB    ww  ",
	"   www      wwwwBB    ww  ",
	"  ww        wwBB    wwww  ",
	"  ww        wwBB    wwww  ",
	"  wwwwww    BB    ww      ",
	"      ww    BB    ww      ",
	"                  ww    ww",
	"           pppp       wwww",
	"           pe p           ",
	"wwww       p  p           "
},
{ // STAGE 8
	"    bb    bb      bb      ",
	"    bb    bb  bb  bb      ",
	"BBbbbbbb  bb      bbb     ",
	"BBbbbbbb  bb  ww  bbb     ",
	"BBBBBB    bb  bb  bb   bb ",
	"BBBBBB        bb       bb ",
	"BBWWWWWWWWWWWWWWWWWWWW  WW",
	"BBWWWWWWWWWWWWWWWWWWWW  WW",
	"  bb                      ",
	"  bb        bbbb          ",
	"    bb     bbbbbbbbbbbwwww",
	"    bb     bbbbb  bb      ",
	"bbbb  bb   bbbbbBBbb    bb",
	"bbbb  bb   bbbbbBBbbwwwwbb",
	"      ww      BBBBBBBB    ",
	"      ww  ww  BBBBBBBB    ",
	"WWWW  WWWWWWWWWW  WWWWWWWW",
	"WWWW  WWWWWWWWWW  WWWWWWWW",
	"BBBB   b                  ",
	"BBBB   b    bbbb          ",
	"BBBBbb  b      b      bb  ",
	"BBBBbb  b      b  wwbbbb  ",
	"BB  bb  b         bb  bb  ",
	"BBwwbb  b  pppp       bb  ",
	"           pe p       bb  ",
	"           p  p   bb      "
},
{ // EMPTY STAGE
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"           pppp           ",
	"           pe p           ",
	"           p  p           "
}
};

const uint8_t tanks[36][20] = {
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1},
	{3, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 3, 3},
	{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 3, 3, 3},
	{2, 2, 2, 2, 2, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1},
	{2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3},
	{0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0},
	{2, 2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0}
};