#include <string>

const std::string stages[36][26] = {
{ // STAGE 1
	"                          ",
	"                          ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bbwwbb  bb  bb  ",
	"  bb  bb  bbwwbb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb          bb  bb  ",
	"  bb  bb          bb  bb  ",
	"          bb  bb          ",
	"          bb  bb          ",
	"bb  bbbb          bbbb  bb",
	"ww  bbbb          bbbb  ww",
	"          bb  bb          ",
	"          bbbbbb          ",
	"  bb  bb  bbbbbb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb  bb  bb  bb  bb  ",
	"  bb  bb          bb  bb  ",
	"  bb  bb          bb  bb  ",
	"  bb  bb   pppp   bb  bb  ",
	"           pe p           ",
	"           p  p           "
},
{ // STAGE 2
	"      ww      ww          ",
	"      ww      ww          ",
	"  bb  ww      bb  bb  bb  ",
	"  bb  ww      bb  bb  bb  ",
	"  bb        bbbb  bbwwbb  ",
	"  bb        bbbb  bbwwbb  ",
	"      bb          ww      ",
	"      bb          ww      ",
	"BB    bb    ww    bbBBbbww",
	"BB    bb    ww    bbBBbbww",
	"BBBB      bb    ww  BB    ",
	"BBBB      bb    ww  BB    ",
	"  bbbbbbBBBBBBww    BBbb  ",
	"  bbbbbbBBBBBBww    BBbb  ",
	"      wwBBbb  bb  bb  bb  ",
	"      wwBBbb  bb  bb  bb  ",
	"wwbb  ww  bb  bb      bb  ",
	"wwbb  ww  bb  bb      bb  ",
	"  bb  bb  bbbbbb  bbwwbb  ",
	"  bb  bb  bbbbbb  bbwwbb  ",
	"  bb  bb  bbbbbb          ",
	"  bb  bb  bbbbbb          ",
	"  bb              bb  bb  ",
	"  bb       pppp   bb  bb  ",
	"  bb  bb   pe p   bbbbbb  ",
	"  bb  bb   p  p   bbbbbb  "
},
{ // EMPTY STAGE
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          ",
	"                          "
}
};